all: butson_n24_note.pdf

butson_n24_note.pdf: butson_n24_note.tex
	pdflatex butson_n24_note.tex
	pdflatex butson_n24_note.tex
	rm -f butson_n24_note.aux butson_n24_note.log butson_n24_note.out

clean:
	rm -f butson_n24_note.pdf butson_n24_note.aux butson_n24_note.log butson_n24_note.out
